// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechnologyLibrary.Models;

#nullable disable

namespace TechnologyLibrary.Migrations
{
    [DbContext(typeof(ZelisTechnologyDBContext))]
    partial class ZelisTechnologyDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechnologyLibrary.Models.Technology", b =>
                {
                    b.Property<int>("TechnologyId")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("CHAR(1)");

                    b.Property<string>("TechnologyName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)");

                    b.HasKey("TechnologyId");

                    b.ToTable("Technology");
                });
#pragma warning restore 612, 618
        }
    }
}
